FROM node:16.10

RUN apt-get update && \
    apt-get install -qq -y build-essential nodejs yarn

WORKDIR /app
COPY . .
WORKDIR /app/InvoiceAppClient

# RUN npm install
RUN npm install -g @angular/cli

ENTRYPOINT ["ng", "serve", "--host", "0.0.0.0"]